-- 10 seed tools for local development — paste after schema.sql
-- All prices in USD, converted at display time

insert into tools (name, slug, name_ar, category, description_ar, pricing, price_from, use_cases, official_url, features, is_free_tier) values

('ChatGPT', 'chatgpt', 'تشات جي بي تي', 'writing',
 'مساعد ذكاء اصطناعي من OpenAI للكتابة والمحادثة وحل المسائل. الأشهر في العالم.',
 'freemium', 20,
 ARRAY['كتابة','تسويق','تعليم','برمجة'],
 'https://chat.openai.com',
 '{"ar":["يكتب بالعربية","يجيب على الأسئلة","يلخص النصوص"],"en":["Write code","Answer questions","Summarize text"]}',
 true),

('Gemini', 'gemini', 'جيميني', 'writing',
 'مساعد الذكاء الاصطناعي من Google. مجاني بالكامل مع دعم جيد للعربية.',
 'freemium', 20,
 ARRAY['كتابة','بحث','تعليم'],
 'https://gemini.google.com',
 '{"ar":["يدعم العربية بشكل ممتاز","يبحث على الإنترنت","مجاني"],"en":["Google Search integration","Free tier","Multimodal"]}',
 true),

('Midjourney', 'midjourney', 'ميدجورني', 'image',
 'أفضل أداة لتوليد الصور بالذكاء الاصطناعي. جودة استثنائية للتصميم والفن الرقمي.',
 'مدفوع', 10,
 ARRAY['تصميم','فن','تسويق'],
 'https://midjourney.com',
 '{"ar":["جودة صور عالية جداً","أسلوب فني مميز","تصاميم احترافية"],"en":["High quality images","Artistic styles","Commercial license"]}',
 false),

('Claude', 'claude', 'كلود', 'writing',
 'مساعد Anthropic للكتابة والتحليل. يتميز بفهم السياق الطويل وكتابة نصوص عالية الجودة.',
 'freemium', 20,
 ARRAY['كتابة','تحليل','برمجة','تعليم'],
 'https://claude.ai',
 '{"ar":["نصوص عالية الجودة","يفهم السياق الطويل","دقيق في المعلومات"],"en":["Long context","Accurate responses","Code review"]}',
 true),

('DALL-E 3', 'dalle-3', 'دالي 3', 'image',
 'مولّد الصور من OpenAI. متاح عبر ChatGPT Plus ومباشرة عبر API.',
 'مدفوع', 20,
 ARRAY['تصميم','إبداع','تسويق'],
 'https://openai.com/dall-e-3',
 '{"ar":["دقة في اتباع التعليمات","متاح في ChatGPT Plus","جودة عالية"],"en":["Instruction following","High resolution","API access"]}',
 false),

('Perplexity', 'perplexity', 'بيربلكسيتي', 'writing',
 'محرك بحث بالذكاء الاصطناعي. يجيب بمصادر موثقة. بديل ذكي لـ Google.',
 'freemium', 20,
 ARRAY['بحث','تعليم','صحافة'],
 'https://perplexity.ai',
 '{"ar":["يذكر المصادر","يبحث على الإنترنت","إجابات موثوقة"],"en":["Cited sources","Real-time search","Academic mode"]}',
 true),

('GitHub Copilot', 'github-copilot', 'كوبايلوت', 'code',
 'مساعد البرمجة من GitHub وMicrosoft. يكمل الكود تلقائياً في أي IDE.',
 'مدفوع', 10,
 ARRAY['برمجة','تطوير'],
 'https://github.com/features/copilot',
 '{"ar":["يكمل الكود تلقائياً","يدعم جميع اللغات","يشرح الكود"],"en":["Autocomplete","All IDEs","Chat mode"]}',
 false),

('ElevenLabs', 'elevenlabs', 'إيليفن لابس', 'audio',
 'أفضل أداة لتحويل النص لصوت. أصوات واقعية جداً وتدعم العربية.',
 'freemium', 5,
 ARRAY['صوت','محتوى','تعليم','إعلان'],
 'https://elevenlabs.io',
 '{"ar":["صوت عربي طبيعي","استنساخ الصوت","100 لغة"],"en":["Voice cloning","Arabic support","API access"]}',
 true),

('Runway', 'runway', 'رانواي', 'video',
 'أقوى أداة لتوليد وتحرير الفيديو بالذكاء الاصطناعي. تحويل الصور لفيديو.',
 'freemium', 12,
 ARRAY['فيديو','إبداع','تسويق'],
 'https://runwayml.com',
 '{"ar":["توليد فيديو من صورة","تحرير بالنص","جودة سينمائية"],"en":["Text to video","Image to video","Inpainting"]}',
 true),

('Notion AI', 'notion-ai', 'نوشن AI', 'writing',
 'مساعد الكتابة المدمج في Notion. يساعد في الملاحظات والمستندات والمشاريع.',
 'مدفوع', 10,
 ARRAY['كتابة','تنظيم','عمل'],
 'https://notion.so/product/ai',
 '{"ar":["مدمج في Notion","يلخص الملاحظات","يكتب القوالب"],"en":["Built-in AI","Summarize","Templates"]}',
 false);
