-- 10 additional tools — run after seed.sql (schema + first 10 already inserted)
-- All prices in USD, converted at display time

insert into tools (name, slug, name_ar, category, description_ar, pricing, price_from, use_cases, official_url, features, is_free_tier) values

('Cursor', 'cursor', 'كيرسر', 'code',
 'محرر كود ذكي مبني على VS Code. يفهم قاعدة الكود كاملة ويكتب ويعدل الكود بالمحادثة.',
 'freemium', 20,
 ARRAY['برمجة','تطوير'],
 'https://cursor.com',
 '{"ar":["يفهم المشروع كاملاً","يعدل ملفات متعددة","يشرح الكود"],"en":["Codebase context","Multi-file edits","Chat with code"]}',
 true),

('Canva AI', 'canva-ai', 'كانفا AI', 'image',
 'أداة التصميم الأشهر مع ذكاء اصطناعي. يولّد صوراً ويزيل الخلفيات ويصمم تلقائياً.',
 'freemium', 15,
 ARRAY['تصميم','تسويق','إبداع','عمل'],
 'https://canva.com',
 '{"ar":["سهل الاستخدام","قوالب عربية","يزيل الخلفيات"],"en":["Magic design","Background remover","Brand kit"]}',
 true),

('Suno', 'suno', 'سونو', 'audio',
 'يولّد أغاني كاملة بالكلمات والموسيقى من نص. أفضل أداة لتوليد الموسيقى بالذكاء الاصطناعي.',
 'freemium', 10,
 ARRAY['صوت','إبداع','محتوى'],
 'https://suno.com',
 '{"ar":["أغاني كاملة من نص","أصوات بشرية واقعية","أنواع موسيقى متعددة"],"en":["Full song generation","Lyrics + music","Multiple genres"]}',
 true),

('Synthesia', 'synthesia', 'سينثيزيا', 'video',
 'يصنع فيديوهات احترافية بأفاتار بشري ناطق. مثالي للتدريب والتسويق بدون كاميرا.',
 'مدفوع', 29,
 ARRAY['فيديو','تسويق','تعليم','عمل'],
 'https://synthesia.io',
 '{"ar":["أفاتار يتكلم عربي","بدون كاميرا أو ميكروفون","أكثر من 120 لغة"],"en":["AI avatars","120+ languages","No camera needed"]}',
 false),

('Jasper AI', 'jasper-ai', 'جاسبر AI', 'writing',
 'أداة الكتابة التسويقية الاحترافية. يكتب إعلانات ومقالات وبريد إلكتروني بأسلوب علامتك التجارية.',
 'مدفوع', 39,
 ARRAY['كتابة','تسويق','إعلان','عمل'],
 'https://jasper.ai',
 '{"ar":["يتعلم أسلوب علامتك","قوالب تسويقية جاهزة","يكتب بلغات متعددة"],"en":["Brand voice","Marketing templates","50+ languages"]}',
 false),

('Leonardo AI', 'leonardo-ai', 'ليوناردو AI', 'image',
 'منصة متقدمة لتوليد الصور. يتميز بنماذج مخصصة للألعاب والفن والشخصيات.',
 'freemium', 12,
 ARRAY['تصميم','إبداع','فن','ألعاب'],
 'https://leonardo.ai',
 '{"ar":["نماذج متخصصة للألعاب","جودة عالية","تحكم دقيق بالتفاصيل"],"en":["Game assets","Custom models","Fine control"]}',
 true),

('Grammarly', 'grammarly', 'جرامرلي', 'writing',
 'المساعد الأشهر لتصحيح الكتابة الإنجليزية. يصحح الإملاء والنحو ويحسن الأسلوب.',
 'freemium', 12,
 ARRAY['كتابة','تعليم','عمل'],
 'https://grammarly.com',
 '{"ar":["تصحيح فوري للإنجليزية","يحسن الأسلوب","متوفر كـ extension"],"en":["Grammar check","Style suggestions","Plagiarism check"]}',
 true),

('Murf AI', 'murf-ai', 'مرف AI', 'audio',
 'يحوّل النص لصوت بشري احترافي. أصوات عربية متاحة مناسبة للبودكاست والإعلانات.',
 'freemium', 29,
 ARRAY['صوت','محتوى','إعلان','تعليم'],
 'https://murf.ai',
 '{"ar":["أصوات عربية طبيعية","تحكم بالنبرة والسرعة","مناسب للبودكاست"],"en":["120+ voices","Arabic support","Studio quality"]}',
 true),

('Replit AI', 'replit-ai', 'ريبلت AI', 'code',
 'بيئة برمجة كاملة في المتصفح مع ذكاء اصطناعي. يشرح ويصحح ويكتب كوداً في الوقت الفعلي.',
 'freemium', 25,
 ARRAY['برمجة','تعليم','تطوير'],
 'https://replit.com',
 '{"ar":["برمجة بدون إعداد","يصحح الأخطاء تلقائياً","مشاركة فورية"],"en":["Browser IDE","AI debugging","Instant deploy"]}',
 true),

('Adobe Firefly', 'adobe-firefly', 'أدوبي فايرفلاي', 'image',
 'مولّد صور Adobe مصمم للاستخدام التجاري. آمن قانونياً ومتكامل مع Photoshop و Illustrator.',
 'freemium', 5,
 ARRAY['تصميم','تسويق','إبداع'],
 'https://firefly.adobe.com',
 '{"ar":["آمن تجارياً 100%","مدمج في Photoshop","جودة احترافية"],"en":["Commercially safe","Photoshop integration","Generative fill"]}',
 true);
