import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
const supabase = createClient(supabaseUrl, supabaseKey)

// affiliate_url: fill after registering — programs marked with [AFFILIATE]
const tools = [
  // ─── WRITING ────────────────────────────────────────────────────────────────
  {
    name: 'ChatGPT',
    slug: 'chatgpt',
    name_ar: 'شات جي بي تي',
    category: 'writing',
    description_ar: 'مساعد الذكاء الاصطناعي الأشهر من OpenAI. يكتب المقالات والكود والبريد الإلكتروني بأوامر بسيطة بالعربية.',
    pricing: 'freemium',
    price_from: 20,
    price_currency: 'USD',
    use_cases: ['كتابة', 'بحث', 'ترجمة', 'تلخيص', 'برمجة', 'إجابة أسئلة'],
    official_url: 'https://chatgpt.com',
    affiliate_url: null,
    features: {
      ar: ['يكتب بأي لغة بما فيها العربية', 'يفهم السياق ويتذكر المحادثة', 'يصحح الأكواد البرمجية', 'GPT-4o في الخطة المجانية'],
      en: ['Multilingual including Arabic', 'Context-aware conversation', 'Code generation & debugging', 'GPT-4o in free plan'],
    },
    is_free_tier: true,
  },
  {
    name: 'Claude',
    slug: 'claude',
    name_ar: 'كلود',
    category: 'writing',
    description_ar: 'مساعد ذكاء اصطناعي من Anthropic. يتميز بفهم عميق للنصوص الطويلة والكتابة الإبداعية عالية الجودة.',
    pricing: 'freemium',
    price_from: 20,
    price_currency: 'USD',
    use_cases: ['كتابة', 'تحليل', 'بحث', 'ترجمة', 'برمجة', 'تلخيص'],
    official_url: 'https://claude.ai',
    affiliate_url: null,
    features: {
      ar: ['يقرأ ملفات PDF والمستندات', 'نافذة سياق ضخمة 200K توكن', 'كتابة إبداعية متميزة', 'تحليل عميق للبيانات والأكواد'],
      en: ['PDF & document reading', '200K token context window', 'High-quality creative writing', 'Deep code & data analysis'],
    },
    is_free_tier: true,
  },
  {
    name: 'Gemini',
    slug: 'gemini',
    name_ar: 'جيميني',
    category: 'writing',
    description_ar: 'مساعد الذكاء الاصطناعي من Google. متكامل مع خدمات Google مثل Docs وGmail وDrive.',
    pricing: 'freemium',
    price_from: 20,
    price_currency: 'USD',
    use_cases: ['كتابة', 'بحث', 'ترجمة', 'تلخيص', 'إجابة أسئلة'],
    official_url: 'https://gemini.google.com',
    affiliate_url: null,
    features: {
      ar: ['متكامل مع Google Workspace', 'يبحث في الإنترنت مباشرة', 'يحلل الصور والمستندات', 'مجاني مع حساب Google'],
      en: ['Google Workspace integration', 'Real-time web search', 'Image & document analysis', 'Free with Google account'],
    },
    is_free_tier: true,
  },
  {
    name: 'Jasper AI',
    slug: 'jasper',
    name_ar: 'جاسبر',
    category: 'writing',
    description_ar: 'أداة كتابة تسويقية احترافية بالذكاء الاصطناعي. متخصصة في المحتوى الإعلاني والمقالات وسوشال ميديا.',
    pricing: 'مدفوع',
    price_from: 49,
    price_currency: 'USD',
    use_cases: ['تسويق', 'كتابة', 'إعلانات', 'سوشال ميديا', 'مقالات SEO'],
    official_url: 'https://jasper.ai',
    affiliate_url: null, // [AFFILIATE] jasper.ai/affiliates — يدفع 25% عمولة متكررة
    features: {
      ar: ['50+ قالب تسويقي جاهز', 'كتابة محتوى محسّن لـ SEO', 'يدعم 25 لغة', 'يحفظ أسلوب علامتك التجارية'],
      en: ['50+ marketing templates', 'SEO-optimized content', '25 languages', 'Brand voice memory'],
    },
    is_free_tier: false,
  },
  {
    name: 'Copy.ai',
    slug: 'copyai',
    name_ar: 'كوبي إيه آي',
    category: 'writing',
    description_ar: 'أداة كتابة تسويقية سهلة الاستخدام. تولّد نصوص إعلانية وأوصاف منتجات وبريد إلكتروني في ثوانٍ.',
    pricing: 'freemium',
    price_from: 49,
    price_currency: 'USD',
    use_cases: ['تسويق', 'كتابة', 'إعلانات', 'محتوى تجاري'],
    official_url: 'https://copy.ai',
    affiliate_url: null, // [AFFILIATE] copy.ai/affiliates — 45% عمولة
    features: {
      ar: ['90+ أداة كتابة متخصصة', 'خطة مجانية سخية', 'يكتب بلغات متعددة', 'سير عمل آلية للمحتوى'],
      en: ['90+ copywriting tools', 'Generous free plan', 'Multilingual', 'Automated content workflows'],
    },
    is_free_tier: true,
  },
  {
    name: 'Writesonic',
    slug: 'writesonic',
    name_ar: 'رايت سونيك',
    category: 'writing',
    description_ar: 'منصة كتابة AI شاملة تشمل مقالات ومحتوى SEO وإعلانات ومحادثة ذكية تشبه ChatGPT.',
    pricing: 'freemium',
    price_from: 16,
    price_currency: 'USD',
    use_cases: ['كتابة', 'مقالات SEO', 'إعلانات', 'تسويق'],
    official_url: 'https://writesonic.com',
    affiliate_url: null, // [AFFILIATE] writesonic.com/affiliate — 30% عمولة متكررة
    features: {
      ar: ['يكتب مقالات طويلة كاملة', 'محسّن لـ SEO', 'Chatsonic مثل ChatGPT مع بحث', 'أسعار تنافسية'],
      en: ['Long-form article writer', 'SEO-optimized output', 'Chatsonic with web search', 'Competitive pricing'],
    },
    is_free_tier: true,
  },
  {
    name: 'Rytr',
    slug: 'rytr',
    name_ar: 'رايتر',
    category: 'writing',
    description_ar: 'أداة كتابة AI اقتصادية للمبتدئين. تغطي 40+ حالة استخدام وتدعم العربية بخطة مجانية كريمة.',
    pricing: 'freemium',
    price_from: 9,
    price_currency: 'USD',
    use_cases: ['كتابة', 'سوشال ميديا', 'بريد إلكتروني', 'إعلانات'],
    official_url: 'https://rytr.me',
    affiliate_url: null, // [AFFILIATE] rytr.me/affiliate — 30% عمولة
    features: {
      ar: ['40+ حالة استخدام جاهزة', 'أرخص خطة في السوق $9/شهر', 'خطة مجانية 10K حرف/شهر', 'يدعم 30 لغة'],
      en: ['40+ use cases', 'Cheapest plan at $9/mo', 'Free plan 10K chars/month', '30 languages'],
    },
    is_free_tier: true,
  },
  {
    name: 'Notion AI',
    slug: 'notion-ai',
    name_ar: 'نوشن AI',
    category: 'writing',
    description_ar: 'ذكاء اصطناعي مدمج داخل Notion. يلخص الملاحظات ويكتب المستندات ويحلل محتوى مساحة عملك.',
    pricing: 'freemium',
    price_from: 10,
    price_currency: 'USD',
    use_cases: ['كتابة', 'تلخيص', 'إنتاجية', 'إدارة مشاريع'],
    official_url: 'https://notion.so/product/ai',
    affiliate_url: null,
    features: {
      ar: ['مدمج مباشرة في Notion', 'يلخص صفحاتك ومستنداتك', 'يكتب داخل سياق ملاحظاتك', 'لا تحتاج تبديل التطبيقات'],
      en: ['Native Notion integration', 'Summarizes your pages', 'Writes in your notes context', 'No app switching'],
    },
    is_free_tier: true,
  },
  {
    name: 'Grammarly',
    slug: 'grammarly',
    name_ar: 'جراماري',
    category: 'writing',
    description_ar: 'أداة تصحيح القواعد والأسلوب الأشهر. تعمل في المتصفح والبريد الإلكتروني ومحررات النص.',
    pricing: 'freemium',
    price_from: 12,
    price_currency: 'USD',
    use_cases: ['كتابة', 'تصحيح إملائي', 'بريد إلكتروني', 'مقالات'],
    official_url: 'https://grammarly.com',
    affiliate_url: null, // [AFFILIATE] grammarly.com/affiliates — $0.20 لكل تثبيت مجاني + $20 للاشتراك
    features: {
      ar: ['يصحح القواعد والإملاء', 'يحسّن أسلوب الكتابة', 'إضافة للمتصفح مجانية', 'يعمل مع Gmail وDocs'],
      en: ['Grammar & spell check', 'Writing style improvement', 'Free browser extension', 'Gmail & Docs integration'],
    },
    is_free_tier: true,
  },
  {
    name: 'QuillBot',
    slug: 'quillbot',
    name_ar: 'كويل بوت',
    category: 'writing',
    description_ar: 'أداة إعادة الصياغة الأشهر. تعيد كتابة الجمل بأساليب مختلفة وتلخص النصوص الطويلة.',
    pricing: 'freemium',
    price_from: 10,
    price_currency: 'USD',
    use_cases: ['كتابة', 'إعادة صياغة', 'تلخيص', 'ترجمة'],
    official_url: 'https://quillbot.com',
    affiliate_url: null, // [AFFILIATE] quillbot.com/affiliate
    features: {
      ar: ['7 أوضاع إعادة صياغة', 'ملخص ذكي للنصوص', 'تحسين تلقائي للجمل', 'إضافة للمتصفح مجانية'],
      en: ['7 paraphrasing modes', 'Text summarizer', 'Auto sentence enhancement', 'Free browser extension'],
    },
    is_free_tier: true,
  },

  // ─── IMAGE ──────────────────────────────────────────────────────────────────
  {
    name: 'Midjourney',
    slug: 'midjourney',
    name_ar: 'ميدجورني',
    category: 'image',
    description_ar: 'أشهر أداة توليد صور بالذكاء الاصطناعي. تنتج صوراً فنية خيالية بجودة احترافية من وصف نصي.',
    pricing: 'مدفوع',
    price_from: 10,
    price_currency: 'USD',
    use_cases: ['تصميم', 'فن رقمي', 'إبداع', 'توليد صور', 'إعلانات'],
    official_url: 'https://midjourney.com',
    affiliate_url: null,
    features: {
      ar: ['أعلى جودة صور في السوق', 'يعمل عبر Discord', 'تحكم دقيق بالأسلوب الفني', 'مجتمع ضخم وإلهام مستمر'],
      en: ['Highest image quality', 'Works via Discord', 'Fine style control', 'Large community'],
    },
    is_free_tier: false,
  },
  {
    name: 'Adobe Firefly',
    slug: 'adobe-firefly',
    name_ar: 'أدوبي فايرفلاي',
    category: 'image',
    description_ar: 'توليد صور AI من Adobe. مدمج مع Photoshop وIllustrator، مرخّص تجارياً 100%.',
    pricing: 'freemium',
    price_from: 5,
    price_currency: 'USD',
    use_cases: ['تصميم', 'توليد صور', 'تحرير صور', 'إعلانات'],
    official_url: 'https://firefly.adobe.com',
    affiliate_url: null,
    features: {
      ar: ['مدمج في Photoshop مباشرة', 'مرخّص تجارياً آمن', 'تحرير انتقائي بالذكاء الاصطناعي', '25 صورة مجانية شهرياً'],
      en: ['Native Photoshop integration', 'Commercially safe', 'Generative fill & expand', '25 free credits/month'],
    },
    is_free_tier: true,
  },
  {
    name: 'Leonardo AI',
    slug: 'leonardo-ai',
    name_ar: 'ليوناردو AI',
    category: 'image',
    description_ar: 'منصة توليد صور AI احترافية مع نماذج متخصصة للألعاب والفن والإعلانات. خطة مجانية سخية.',
    pricing: 'freemium',
    price_from: 10,
    price_currency: 'USD',
    use_cases: ['توليد صور', 'ألعاب', 'فن رقمي', 'تصميم'],
    official_url: 'https://leonardo.ai',
    affiliate_url: null, // [AFFILIATE] leonardo.ai - لديهم برنامج affiliate
    features: {
      ar: ['150 صورة مجانية يومياً', 'نماذج متخصصة للألعاب', 'تحكم متقدم بالأبعاد والأسلوب', 'مجتمع نماذج مفتوحة'],
      en: ['150 free images/day', 'Game-specialized models', 'Advanced style control', 'Community model library'],
    },
    is_free_tier: true,
  },
  {
    name: 'Canva AI',
    slug: 'canva-ai',
    name_ar: 'كانفا AI',
    category: 'image',
    description_ar: 'أدوات الذكاء الاصطناعي المدمجة في Canva. توليد صور ومزيل خلفية وتحرير سحري كل في مكان واحد.',
    pricing: 'freemium',
    price_from: 15,
    price_currency: 'USD',
    use_cases: ['تصميم', 'توليد صور', 'سوشال ميديا', 'عروض تقديمية'],
    official_url: 'https://canva.com/ai-image-generator',
    affiliate_url: null, // [AFFILIATE] canva.com/affiliates — 80% من أول اشتراك
    features: {
      ar: ['مدمج في بيئة Canva الكاملة', 'مزيل خلفية تلقائي', 'توليد صور بالنص', 'قوالب جاهزة لكل منصة'],
      en: ['Built into Canva ecosystem', 'Auto background remover', 'Text-to-image generation', 'Platform-ready templates'],
    },
    is_free_tier: true,
  },
  {
    name: 'Ideogram',
    slug: 'ideogram',
    name_ar: 'أيديوغرام',
    category: 'image',
    description_ar: 'أداة توليد صور AI متخصصة في دمج النصوص داخل الصور. مثالية لتصميم الشعارات والبطاقات.',
    pricing: 'freemium',
    price_from: 8,
    price_currency: 'USD',
    use_cases: ['توليد صور', 'تصميم', 'شعارات', 'بطاقات'],
    official_url: 'https://ideogram.ai',
    affiliate_url: null,
    features: {
      ar: ['أفضل أداة لإضافة نص داخل الصور', 'جودة عالية مجاناً', 'تصاميم شعارات احترافية', 'واجهة بسيطة'],
      en: ['Best text-in-image rendering', 'High quality free tier', 'Professional logo designs', 'Simple interface'],
    },
    is_free_tier: true,
  },
  {
    name: 'DALL-E 3',
    slug: 'dalle-3',
    name_ar: 'دالي 3',
    category: 'image',
    description_ar: 'نموذج توليد الصور من OpenAI. مدمج في ChatGPT Plus ويفهم التعليمات المعقدة بدقة عالية.',
    pricing: 'freemium',
    price_from: 20,
    price_currency: 'USD',
    use_cases: ['توليد صور', 'إبداع', 'تصميم', 'إعلانات'],
    official_url: 'https://openai.com/dall-e-3',
    affiliate_url: null,
    features: {
      ar: ['مدمج في ChatGPT Plus', 'يفهم وصف معقد ودقيق', 'يرفض إنشاء محتوى ضار', 'جودة فوتوريالستيك'],
      en: ['Built into ChatGPT Plus', 'Understands complex prompts', 'Safety filters built-in', 'Photorealistic quality'],
    },
    is_free_tier: false,
  },
  {
    name: 'Flux AI',
    slug: 'flux-ai',
    name_ar: 'فلكس AI',
    category: 'image',
    description_ar: 'نموذج توليد صور مفتوح المصدر من Black Forest Labs. منافس قوي لـ Midjourney بتفاصيل واقعية مذهلة.',
    pricing: 'freemium',
    price_from: 10,
    price_currency: 'USD',
    use_cases: ['توليد صور', 'فن رقمي', 'تصميم', 'فوتوريالستيك'],
    official_url: 'https://blackforestlabs.ai',
    affiliate_url: null,
    features: {
      ar: ['تفاصيل واقعية استثنائية', 'مفتوح المصدر جزئياً', 'متاح عبر منصات متعددة', 'يدعم الأيدي والوجوه بدقة'],
      en: ['Exceptional photorealism', 'Partially open-source', 'Available on multiple platforms', 'Accurate hands & faces'],
    },
    is_free_tier: true,
  },

  // ─── CODE ───────────────────────────────────────────────────────────────────
  {
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    name_ar: 'جيت هاب كوبايلت',
    category: 'code',
    description_ar: 'مساعد البرمجة من GitHub وOpenAI. يكمل الكود تلقائياً ويشرح الأخطاء ويولّد دوال كاملة.',
    pricing: 'مدفوع',
    price_from: 10,
    price_currency: 'USD',
    use_cases: ['برمجة', 'إكمال كود', 'إصلاح أخطاء', 'كتابة اختبارات'],
    official_url: 'https://github.com/features/copilot',
    affiliate_url: null,
    features: {
      ar: ['مدمج في VS Code وJetBrains', 'يكمل الكود أثناء الكتابة', 'يشرح الكود ويكتب التوثيق', 'مجاني للطلاب والمصادر المفتوحة'],
      en: ['VS Code & JetBrains integration', 'Real-time code completion', 'Code explanation & docs', 'Free for students & OSS'],
    },
    is_free_tier: false,
  },
  {
    name: 'Cursor',
    slug: 'cursor',
    name_ar: 'كيرسر',
    category: 'code',
    description_ar: 'محرر كود بالذكاء الاصطناعي. مبني على VS Code مع قدرة على فهم مشروعك كاملاً وتعديل ملفات متعددة.',
    pricing: 'freemium',
    price_from: 20,
    price_currency: 'USD',
    use_cases: ['برمجة', 'تطوير برمجيات', 'إصلاح أخطاء', 'refactoring'],
    official_url: 'https://cursor.com',
    affiliate_url: null,
    features: {
      ar: ['يفهم قاعدة كودك كاملة', 'يعدّل ملفات متعددة في آن واحد', 'مبني على VS Code — مألوف فوراً', 'Composer لتطوير ميزات كاملة'],
      en: ['Understands full codebase', 'Multi-file edits', 'Built on VS Code', 'Composer for full features'],
    },
    is_free_tier: true,
  },
  {
    name: 'Tabnine',
    slug: 'tabnine',
    name_ar: 'تابناين',
    category: 'code',
    description_ar: 'مساعد برمجة AI يعمل محلياً على جهازك. خيار مثالي من يريد الخصوصية وعدم إرسال كوده للسحابة.',
    pricing: 'freemium',
    price_from: 12,
    price_currency: 'USD',
    use_cases: ['برمجة', 'إكمال كود', 'خصوصية'],
    official_url: 'https://tabnine.com',
    affiliate_url: null, // [AFFILIATE] tabnine.com/affiliates
    features: {
      ar: ['يعمل محلياً على جهازك للخصوصية', 'يدعم 30+ لغة برمجة', 'يتعلم من كودك الخاص', 'خطة مجانية دائمة'],
      en: ['Local AI for privacy', '30+ programming languages', 'Learns from your code', 'Forever free plan'],
    },
    is_free_tier: true,
  },
  {
    name: 'Codeium',
    slug: 'codeium',
    name_ar: 'كوديوم',
    category: 'code',
    description_ar: 'بديل مجاني لـ GitHub Copilot. إكمال كود ذكي مجاناً للأفراد مع دعم 70+ لغة برمجة.',
    pricing: 'مجاني',
    price_from: null,
    price_currency: 'USD',
    use_cases: ['برمجة', 'إكمال كود', 'إصلاح أخطاء'],
    official_url: 'https://codeium.com',
    affiliate_url: null,
    features: {
      ar: ['مجاني تماماً للأفراد', '70+ لغة برمجة', 'يعمل في 40+ محرر كود', 'سريع جداً في الاقتراحات'],
      en: ['Completely free for individuals', '70+ programming languages', '40+ IDE support', 'Very fast suggestions'],
    },
    is_free_tier: true,
  },
  {
    name: 'Replit AI',
    slug: 'replit-ai',
    name_ar: 'ريبليت AI',
    category: 'code',
    description_ar: 'بيئة برمجة سحابية مع ذكاء اصطناعي مدمج. برمج وشغّل ونشر تطبيقاتك كلها من المتصفح.',
    pricing: 'freemium',
    price_from: 25,
    price_currency: 'USD',
    use_cases: ['برمجة', 'تعليم', 'نشر تطبيقات', 'نماذج أولية'],
    official_url: 'https://replit.com',
    affiliate_url: null,
    features: {
      ar: ['بيئة تطوير كاملة في المتصفح', 'AI يكتب التطبيقات من وصف', 'نشر فوري بدون إعداد', 'مثالي للتعليم والنماذج الأولية'],
      en: ['Full IDE in browser', 'AI builds apps from description', 'Instant deployment', 'Great for learning & prototyping'],
    },
    is_free_tier: true,
  },
  {
    name: 'v0 by Vercel',
    slug: 'v0',
    name_ar: 'في زيرو من فيرسيل',
    category: 'code',
    description_ar: 'أداة توليد واجهات مستخدم بالذكاء الاصطناعي من Vercel. تحوّل الوصف النصي إلى كود React جاهز.',
    pricing: 'freemium',
    price_from: 20,
    price_currency: 'USD',
    use_cases: ['برمجة', 'تصميم UI', 'React', 'نماذج أولية'],
    official_url: 'https://v0.dev',
    affiliate_url: null,
    features: {
      ar: ['يولّد واجهات React من وصف نصي', 'كود جاهز للنسخ والاستخدام', 'يستخدم shadcn/ui وTailwind', 'معاينة حية فورية'],
      en: ['React UI from text description', 'Production-ready code', 'shadcn/ui & Tailwind', 'Live preview'],
    },
    is_free_tier: true,
  },

  // ─── VIDEO ──────────────────────────────────────────────────────────────────
  {
    name: 'RunwayML',
    slug: 'runway',
    name_ar: 'رن واي',
    category: 'video',
    description_ar: 'منصة توليد وتحرير فيديو بالذكاء الاصطناعي. تحوّل الصور والنصوص إلى مقاطع فيديو احترافية.',
    pricing: 'freemium',
    price_from: 15,
    price_currency: 'USD',
    use_cases: ['توليد فيديو', 'تحرير فيديو', 'إبداع', 'إنتاج محتوى'],
    official_url: 'https://runwayml.com',
    affiliate_url: null,
    features: {
      ar: ['توليد فيديو من صورة أو نص', 'إزالة الخلفية تلقائياً', 'تحرير فيديو بالأوامر النصية', '125 كريدت مجاني للبداية'],
      en: ['Text & image to video', 'Auto background removal', 'Text-based video editing', '125 free credits to start'],
    },
    is_free_tier: true,
  },
  {
    name: 'Synthesia',
    slug: 'synthesia',
    name_ar: 'سينثيزيا',
    category: 'video',
    description_ar: 'منصة إنشاء فيديوهات مع أفاتار بشري واقعي. اكتب النص واختر الأفاتار والغة ويولّد الفيديو.',
    pricing: 'مدفوع',
    price_from: 22,
    price_currency: 'USD',
    use_cases: ['توليد فيديو', 'تدريب', 'تسويق', 'محتوى تعليمي'],
    official_url: 'https://synthesia.io',
    affiliate_url: null, // [AFFILIATE] synthesia.io/affiliates — 25% عمولة
    features: {
      ar: ['160+ أفاتار بشري واقعي', 'يدعم 130 لغة', 'فيديوهات تدريب احترافية', 'لا كاميرا ولا ممثلين'],
      en: ['160+ realistic avatars', '130 languages', 'Professional training videos', 'No camera or actors needed'],
    },
    is_free_tier: false,
  },
  {
    name: 'HeyGen',
    slug: 'heygen',
    name_ar: 'هي جن',
    category: 'video',
    description_ar: 'أداة توليد فيديو تسويقي بأفاتار AI. مشهور بتقنية ترجمة الفيديو مع مزامنة الشفاه.',
    pricing: 'freemium',
    price_from: 29,
    price_currency: 'USD',
    use_cases: ['توليد فيديو', 'تسويق', 'ترجمة فيديو', 'محتوى'],
    official_url: 'https://heygen.com',
    affiliate_url: null, // [AFFILIATE] heygen.com — لديهم برنامج affiliate
    features: {
      ar: ['ترجمة فيديو مع مزامنة الشفاه', '100+ أفاتار', 'شخصية مخصصة من صورتك', 'فيديو تسويقي في دقائق'],
      en: ['Video translation with lip sync', '100+ avatars', 'Custom avatar from your photo', 'Marketing videos in minutes'],
    },
    is_free_tier: true,
  },
  {
    name: 'Pictory AI',
    slug: 'pictory',
    name_ar: 'بيكتوري',
    category: 'video',
    description_ar: 'يحوّل المقالات والنصوص إلى فيديوهات تلقائياً. مثالي لإنشاء محتوى يوتيوب من مقالات المدونة.',
    pricing: 'مدفوع',
    price_from: 23,
    price_currency: 'USD',
    use_cases: ['توليد فيديو', 'يوتيوب', 'محتوى تسويقي', 'تحويل مقالات'],
    official_url: 'https://pictory.ai',
    affiliate_url: null, // [AFFILIATE] pictory.ai/affiliate — 50% عمولة لأول 3 أشهر
    features: {
      ar: ['يحوّل المقالة إلى فيديو تلقائياً', 'مكتبة ملايين مقاطع الفيديو والصور', 'يضيف captions تلقائية', 'خيارات صوت احترافية'],
      en: ['Article to video automatically', 'Millions of stock clips', 'Auto captions', 'Professional voiceover options'],
    },
    is_free_tier: false,
  },
  {
    name: 'Sora',
    slug: 'sora',
    name_ar: 'سورا',
    category: 'video',
    description_ar: 'نموذج توليد فيديو من OpenAI. يولّد مقاطع فيديو واقعية ومتسقة من وصف نصي بجودة سينمائية.',
    pricing: 'مدفوع',
    price_from: 20,
    price_currency: 'USD',
    use_cases: ['توليد فيديو', 'إبداع', 'إنتاج محتوى', 'فن رقمي'],
    official_url: 'https://sora.com',
    affiliate_url: null,
    features: {
      ar: ['جودة فيديو سينمائية', 'يفهم قوانين الفيزياء', 'مدمج مع ChatGPT Plus', 'حتى 20 ثانية فيديو'],
      en: ['Cinematic video quality', 'Understands physics', 'Integrated with ChatGPT Plus', 'Up to 20 seconds video'],
    },
    is_free_tier: false,
  },

  // ─── AUDIO ──────────────────────────────────────────────────────────────────
  {
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    name_ar: 'إيليفن لابس',
    category: 'audio',
    description_ar: 'منصة تحويل النص إلى صوت بجودة بشرية مذهلة. تستنسخ الأصوات وتولّد تعليقاً صوتياً احترافياً.',
    pricing: 'freemium',
    price_from: 5,
    price_currency: 'USD',
    use_cases: ['تحويل نص إلى صوت', 'بودكاست', 'محتوى صوتي', 'استنساخ صوت'],
    official_url: 'https://elevenlabs.io',
    affiliate_url: null, // [AFFILIATE] elevenlabs.io/affiliates — 22% عمولة متكررة
    features: {
      ar: ['صوت بشري واقعي 100%', 'يستنسخ صوتك من 1 دقيقة فقط', 'يدعم العربية والإنجليزية', '10K حرف مجاني شهرياً'],
      en: ['100% human-like voice', 'Clone your voice from 1 min', 'Arabic & English support', '10K free chars/month'],
    },
    is_free_tier: true,
  },
  {
    name: 'Murf AI',
    slug: 'murf-ai',
    name_ar: 'مورف AI',
    category: 'audio',
    description_ar: 'استوديو تحويل نص إلى صوت احترافي. 120+ صوت بشري واقعي لتعليق الفيديوهات والبودكاست.',
    pricing: 'freemium',
    price_from: 19,
    price_currency: 'USD',
    use_cases: ['تحويل نص إلى صوت', 'بودكاست', 'تعليق فيديو', 'محتوى صوتي'],
    official_url: 'https://murf.ai',
    affiliate_url: null, // [AFFILIATE] murf.ai — 20% عمولة
    features: {
      ar: ['120+ صوت بشري واقعي', 'يدعم 20 لغة', 'تزامن الصوت مع الفيديو', 'تحكم في السرعة والنبرة'],
      en: ['120+ realistic voices', '20 languages', 'Video sync', 'Speed & pitch control'],
    },
    is_free_tier: true,
  },
  {
    name: 'Descript',
    slug: 'descript',
    name_ar: 'ديسكريبت',
    category: 'audio',
    description_ar: 'أداة تحرير صوت وفيديو ثورية. تحرّر الصوت كأنه نص — احذف الكلام بحذف الكلمات في المستند.',
    pricing: 'freemium',
    price_from: 24,
    price_currency: 'USD',
    use_cases: ['تحرير بودكاست', 'تحرير فيديو', 'نسخ صوتي', 'محتوى صوتي'],
    official_url: 'https://descript.com',
    affiliate_url: null,
    features: {
      ar: ['تحرير الصوت عبر تحرير النص', 'نسخ تلقائي دقيق', 'يزيل أصوات التردد آه وإم', 'استنساخ صوتك'],
      en: ['Edit audio by editing text', 'Accurate auto-transcription', 'Removes filler words', 'Voice cloning'],
    },
    is_free_tier: true,
  },
  {
    name: 'Suno AI',
    slug: 'suno',
    name_ar: 'سونو AI',
    category: 'audio',
    description_ar: 'أداة توليد موسيقى كاملة بالذكاء الاصطناعي. اكتب وصفاً لأغنيتك وستولّد لك موسيقى مع كلمات.',
    pricing: 'freemium',
    price_from: 8,
    price_currency: 'USD',
    use_cases: ['توليد موسيقى', 'إبداع', 'محتوى صوتي'],
    official_url: 'https://suno.ai',
    affiliate_url: null,
    features: {
      ar: ['أغنية كاملة بكلمات وموسيقى', 'كل الأنواع الموسيقية', '50 أغنية مجانية يومياً', 'جودة استثنائية'],
      en: ['Full song with lyrics & music', 'All music genres', '50 free songs/day', 'Exceptional quality'],
    },
    is_free_tier: true,
  },
]

async function seed() {
  console.log(`Seeding ${tools.length} tools...`)

  const { data, error } = await supabase
    .from('tools')
    .upsert(tools, { onConflict: 'slug', ignoreDuplicates: false })
    .select('slug')

  if (error) {
    console.error('Error:', error.message)
    console.error('Details:', error.details)
    process.exit(1)
  }

  console.log(`✓ Inserted/updated ${data?.length ?? 0} tools`)
  console.log('Slugs:', data?.map(t => t.slug).join(', '))
}

seed()
